[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
test = "test/foundry"
cache_path = "forge-cache"
remappings = [
    "@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/",
    "@account-abstraction/=node_modules/@account-abstraction/",
    "@ethereum-waffle/=node_modules/@ethereum-waffle/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat-deploy/=node_modules/hardhat-deploy/",
    "hardhat/=node_modules/hardhat/",
]
via_ir = true
solc_version = "0.8.20"
evm_version = "paris"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
